// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5vRTlrX3G6G7pjlmYE64ntTcEs2jdxE',
    appId: '1:608145427447:web:a0d1869d9264159e58fcf2',
    messagingSenderId: '608145427447',
    projectId: 'assignment-5eadb',
    authDomain: 'assignment-5eadb.firebaseapp.com',
    storageBucket: 'assignment-5eadb.firebasestorage.app',
    measurementId: 'G-YNRL3SPBSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdBdVGSjf7SbGmkotKGY4gJ2S2zjqpRHM',
    appId: '1:608145427447:android:52c62cf3cff2d1e458fcf2',
    messagingSenderId: '608145427447',
    projectId: 'assignment-5eadb',
    storageBucket: 'assignment-5eadb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCZ3XngkY6DcuZvU-srTQyNL9ft12WPA',
    appId: '1:608145427447:ios:3d6b85a81a23098a58fcf2',
    messagingSenderId: '608145427447',
    projectId: 'assignment-5eadb',
    storageBucket: 'assignment-5eadb.firebasestorage.app',
    iosBundleId: 'com.example.topAiAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCZ3XngkY6DcuZvU-srTQyNL9ft12WPA',
    appId: '1:608145427447:ios:3d6b85a81a23098a58fcf2',
    messagingSenderId: '608145427447',
    projectId: 'assignment-5eadb',
    storageBucket: 'assignment-5eadb.firebasestorage.app',
    iosBundleId: 'com.example.topAiAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD5vRTlrX3G6G7pjlmYE64ntTcEs2jdxE',
    appId: '1:608145427447:web:78e78886eed0cff758fcf2',
    messagingSenderId: '608145427447',
    projectId: 'assignment-5eadb',
    authDomain: 'assignment-5eadb.firebaseapp.com',
    storageBucket: 'assignment-5eadb.firebasestorage.app',
    measurementId: 'G-EEHYQJ53LR',
  );

}